sudo: required
services:
    - docker

before_install:
    - docker build -t willgray/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true willgray/react-test npm test

after_success:
    - docker build -t willgray/multi-client ./client
    - docker build -t willgray/multi-nginx ./nginx
    - docker build -t willgray/multi-server ./server
    - docker build -t willgray/multi-worker ./worker
    # Log in to the docker CLI meow
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push willgray/multi-client
    - docker push willgray/multi-nginx
    - docker push willgray/multi-server
    - docker push willgray/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-1-375689575860
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY